### ISSUE TITLE
iOS magnifier re-enabled after submitting form

### ISSUE THREAD

**Issue by dpogue** [scottjehl/Device-Bugs#46]
In iOS you can disable the built-in magnifier gesture using

``` css
* {
    -webkit-user-select: none;
    -webkit-touch-callout: none;
}
```

However, after typing in a text input and submitting the form, the magnifier will be re-enabled.

Able to reproduce in iOS6 and iOS7.
