### ISSUE TITLE
Android 2.3 Ignores Percentage Border Radius

### ISSUE THREAD

**Issue by MethodGrab** [scottjehl/Device-Bugs#57]
## Summary:

Using percentage for border radius will be ignored:

``` scss
.circle { border-radius: 100% } // this will be square
```
## Platforms:
- Android 2.3
## Reduced Example:

http://codepen.io/MethodGrab/full/eNKEKL/
## Workarounds:
- Use pixels

``` scss
.circle { border-radius: 100px }
```
## Links

http://caniuse.com/#search=border-radius -> Known Issues -> 2
http://stackoverflow.com/q/20436102
